name = "VTKFortran"
copyright = "Copyright Â© 2022, Stefano Zaghi"
license = "Multiple licenses"
description = "pure Fortran VTK (XML) API"
maintainer = "Stefano Zaghi"
homepage = "https://github.com/szaghi/VTKFortran"

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[library]
source-dir="src/lib"

[[test]]
name = "vtk_fortran_use_module_basic"
source-dir = "src/tests"
main = "vtk_fortran_use_module_basic.f90"

[[test]]
name = "vtk_fortran_write_pvts"
source-dir = "src/tests"
main = "vtk_fortran_write_pvts.f90"

[[test]]
name = "vtk_fortran_write_volatile"
source-dir = "src/tests"
main = "vtk_fortran_write_volatile.f90"

[[test]]
name = "vtk_fortran_write_vtm"
source-dir = "src/tests"
main = "vtk_fortran_write_vtm.f90"

[[test]]
name = "vtk_fortran_write_vtr"
source-dir = "src/tests"
main = "vtk_fortran_write_vtr.f90"

[[test]]
name = "vtk_fortran_write_vts"
source-dir = "src/tests"
main = "vtk_fortran_write_vts.f90"

[[test]]
name = "vtk_fortran_write_vtu"
source-dir = "src/tests"
main = "vtk_fortran_write_vtu.f90"

[dependencies]
StringiFor = { git = "https://github.com/degawa/StringiFor", branch = "stringifor-fpm" }
FoXy = { git = "https://github.com/degawa/FoXy", branch = "foxy-fpm" }
